[SWE-58] Update Documentation
jackfales/yum pull request #21
Opened 2024-01-01 17:31 UTC by datderek

Task ID: [SWE-58](https://linear.app/swe-dem-boys/issue/SWE-58/update-documentation)
## Status: 🚧 Incomplete 🚧
- Don't really know what to include for the `Local Development` section
- Add examples to API 
## PR Description
Update documentation to make it presentable for resume purposes:
- Comment complicated code for readability
- Mark uncompleted sections with TODO comments
- Update API Documentation
- Update README.md

2024-01-02 20:18 UTC, jackfales commented on README.md
> +[link.](https://documenter.getpostman.com/view/31017970/2s9YkuYy3k)
```suggestion
For documentation on how to utilize our API please see our Postman API [docs.](https://documenter.getpostman.com/view/31017970/2s9YkuYy3k)
```

2024-01-02 20:19 UTC, jackfales commented on README.md
> +# 🛠️ Local Development
This section is fine as is

2024-01-02 20:20 UTC, jackfales commented on app/[user]/page.tsx
> +/* TODO: Remove the imports below and static user data located at `./data` and
Make a linear task where this TODO will be completed and change it to TODO(SWE-XX) where XX is the task id.
```suggestion
/* TODO(SWE-XX): Remove the imports below and static user data located at `./data` and
```

2024-01-02 20:20 UTC, jackfales commented on app/[user]/page.tsx
> +/* TODO: Update generateStaticParams function to query the graphDB for all
Same

2024-01-02 20:21 UTC, jackfales commented on app/[user]/page.tsx
> +/* TODO: Update getProfileData function to query the graphDB for the user data
Same

2024-01-02 20:21 UTC, jackfales commented on app/[user]/page.tsx
> +  /* TODO: Replace this authorization check with a check at the API gateway */
Same

2024-01-02 20:21 UTC, jackfales commented on app/[user]/page.tsx
> +  // TODO: Need to redirect to `/login` similar to `./dashboard/page.tsx`
Same

2024-01-02 20:22 UTC, jackfales commented on app/dashboard/page.tsx
> +//TODO: Remove these constants as these were for the static data
```suggestion
// TODO: Remove these constants as these were for the static data
```

2024-01-02 20:22 UTC, jackfales commented on pages/create-account.tsx
> +
```suggestion

```

2024-01-02 20:24 UTC, jackfales commented on pages/forgot-password.tsx
> +    // Sends an reset password to the email associated with the username
```suggestion
    // Sends an reset password to the email associated with the username
    //
    // TODO: Separate backend from frontend. The following code should be 
    // refactored to an Route Handler. 
    // Similar to what is done in `./app/components/CreatePostModal.tsx`    
```

2024-01-02 20:25 UTC, jackfales requested changes
Update TODOs with linear task IDs for easy tracking

2024-01-04 00:20 UTC, sammyoto requested changes
Overall looks good. Just one comment needs fixing.

2024-01-04 00:20 UTC, sammyoto commented on app/components/EditProfileForm.tsx
SWE-29 just got pulled. May want to pull main to this branch to get updates.

2024-01-04 00:46 UTC, sammyoto approved these changes
Looks good to me.

2024-01-04 22:13 UTC, jackfales approved these changes
Nice work

2024-01-05 01:58 UTC, merged