[SWE-58] Clean Codebase
jackfales/yum pull request #27
Opened 2024-01-23 23:06 UTC by sammyoto

Added prettier and made it run on pre-commit with husky. Added an npm run style:all command and ran it on the codebase, that's why there are so many changes.

2024-01-23 23:09 UTC, sammyoto commented
Some resources I used:
[Husky, Prettier, Eslint tutorial](https://tapajyoti-bose.medium.com/automatically-format-your-code-on-git-commit-using-husky-eslint-prettier-in-9-minutes-4dd6233f32b1)
[Configuring Nextjs with Eslint and Prettier](https://nextjs.org/docs/app/building-your-application/configuring/eslint#prettier)

2024-01-24 19:35 UTC, datderek requested changes
Looks like it ran correctly!

But is there a `.prettierignore` file? It looks like it is running on a lot of files it doesn't have to: Amplify config files, Tailwind config files, README.md, etc.

Nit: Also the default styling looks good, but maybe a `.prettierrc.json` config file should be included so we know what the style standards are.

2024-02-05 16:42 UTC, datderek approved these changes
Look good! Thanks for adding the style and config files.

2024-02-06 18:48 UTC, jackfales commented on README.md
Add the style command to this file

2024-02-06 18:50 UTC, jackfales approved these changes
Nice

2024-02-07 09:03 UTC, merged